#!/bin/bash

runs=(
	# crossing angle 140 urad
	298593

	# crossing angle 130 urad
	298594
	298596

	# crossing angle 120 urad
	298597
)

# when run from DAS
##  source das_block_submitter
##  datasets=(
##  	"/ZeroBias1/Run2017B-PromptReco-v2/AOD"
##  	"/ZeroBias2/Run2017B-PromptReco-v2/AOD"
##  	"/ZeroBias3/Run2017B-PromptReco-v2/AOD"
##  	"/ZeroBias4/Run2017B-PromptReco-v2/AOD"
##  	"/ZeroBias5/Run2017B-PromptReco-v2/AOD"
##  	"/ZeroBias6/Run2017B-PromptReco-v2/AOD"
##  	"/ZeroBias7/Run2017B-PromptReco-v2/AOD"
##  	"/ZeroBias8/Run2017B-PromptReco-v2/AOD"
##  	"/ZeroBias9/Run2017B-PromptReco-v2/AOD"
##  	"/ZeroBias10/Run2017B-PromptReco-v2/AOD"
##  )
##  files_per_block="10"

# when run from EOS
source eos_block_submitter
input_dir="/eos/totem/data/ctpps/reconstruction/2017/alignment_run_July/AOD_skim"
input_filter_command="|grep _skim.root"
files_per_block="1"

output_dir="/eos/totem/data/ctpps/reconstruction/2017/alignment_run_July/version8"

geometry="geometry/2017_preTS2/2017_07_08_fill5912/RP_Dist_Beam_Cent.xml"

alignment_dir="alignment/2017_preTS2/sr+el/version1"
alignment_files="\"CalibPPS/ESProducers/data/alignment/RPixGeometryCorrections-2017-2018.xml\", \"$alignment_dir/45.xml\", \"$alignment_dir/56.xml\""

task_prefix="re_reco_alig_2017_July"
task_suffix="_re_reco"

max_time="14400"

template_file="config/ctpps/2017/alignment_run_July/re_reco_template.py"

required_system="SLCern6"

SubmitBlocks
