#!/bin/bash

source das_block_submitter

runs=(
	# crossing angle 140 urad
	298593

	# crossing angle 130 urad
	298594
	298596

	# crossing angle 120 urad
	298597
)

datasets=(
	"/ZeroBias1/Run2017B-PromptReco-v2/AOD"
	"/ZeroBias2/Run2017B-PromptReco-v2/AOD"
	"/ZeroBias3/Run2017B-PromptReco-v2/AOD"
	"/ZeroBias4/Run2017B-PromptReco-v2/AOD"
	"/ZeroBias5/Run2017B-PromptReco-v2/AOD"
	"/ZeroBias6/Run2017B-PromptReco-v2/AOD"
	"/ZeroBias7/Run2017B-PromptReco-v2/AOD"
	"/ZeroBias8/Run2017B-PromptReco-v2/AOD"
	"/ZeroBias9/Run2017B-PromptReco-v2/AOD"
	"/ZeroBias10/Run2017B-PromptReco-v2/AOD"
)

files_per_block="10"

output_dir="/eos/totem/data/ctpps/reconstruction/2017/alignment_run_July/AOD_skim"

geometry=""

alignment_files=""

task_prefix="skim"
task_suffix="_skim"

max_time="7200"

template_file="config/ctpps/2017/alignment_run_July/skim_template.py"

SubmitBlocks
