#!/bin/bash

source json_submitter

streams=(
	"BTagMu"
	"Commissioning"
	"Charmonium"

	"DoubleMuon"
	"DoubleMuonLowMass"
	"MET"
	"MuOnia"
	"MuonEG"

	"SingleMuon"
	"Tau"
	"ZeroBias"
)

dataset_label="AOD"

dataset_exts=(
	#"Commissioning2018-PromptReco-v1/AOD"

	#"Run2018A-PromptReco-v3/AOD"
	#"Run2018A-PromptReco-v2/AOD"
	#"Run2018A-PromptReco-v1/AOD"

	#"Run2018B-PromptReco-v2/AOD"
	#"Run2018B-PromptReco-v1/AOD"

	#"Run2018C-PromptReco-v3/AOD"
	#"Run2018C-PromptReco-v2/AOD"
	#"Run2018C-PromptReco-v1/AOD"

	#"Run2018D-PromptReco-v2/AOD"
	#"Run2018D-PromptReco-v1/AOD"
)

#streams=("JetHT")
#dataset_exts=(
#	#"Run2018A-17Sep2018-v1/AOD"
#	#"Run2018B-17Sep2018-v1/AOD"
#	#"Run2018C-17Sep2018-v1/AOD"
#	#"Run2018D-PromptReco-v2/AOD"
#)

#streams=("EGamma")
#dataset_exts=(
#	"Run2018A-17Sep2018-v2/AOD"
#	"Run2018B-17Sep2018-v1/AOD"
#	"Run2018C-17Sep2018-v1/AOD"
#	"Run2018D-22Jan2019-v2/AOD"
#)

input_dir="/afs/cern.ch/work/j/jkaspar/analyses/ctpps/alignment/2018/reduction/dataset_definition/json_selected"
input_filter_command="| grep xangle_1[36]0"

output_dir="/eos/cms/store/group/phys_pps/reconstruction/2018/physics_runs/alignment-version4"

geometry=""
alignment_files="\"CalibPPS/ESProducers/data/alignment/RPixGeometryCorrections-2017-2018.xml\""

task_prefix="alignment_re_reco_2018"
task_suffix="_alignment_re_reco"

max_time="86400"

template_file="config/ctpps/2018/physics_fills/alignment_re_reco_template.py"

required_system="SLCern6"

Submit
