#!/bin/bash

source json_submitter

streams=(
	"SingleMuon"
	"ZeroBias"
)

dataset_label="AOD"

dataset_exts=(
	"Run2018A-PromptReco-v3/AOD"
	"Run2018A-PromptReco-v2/AOD"
	"Run2018A-PromptReco-v1/AOD"

	"Run2018B-PromptReco-v2/AOD"
	"Run2018B-PromptReco-v1/AOD"

	"Run2018D-PromptReco-v2/AOD"
	"Run2018D-PromptReco-v1/AOD"
)

input_dir="/afs/cern.ch/work/j/jkaspar/analyses/ctpps/alignment_timing_RP/2018/reduction/dataset_definition/json_selected"
input_filter_command=""

#output_dir="/eos/totem/data/ctpps/reconstruction/2018/physics_runs/timing-version1" # default SW, no alignment
output_dir="/eos/totem/data/ctpps/reconstruction/2018/physics_runs/timing-version2" # SW with geometry fix, no alignment

geometry=""

alignment_files=""
#alignment_files="\"alignment/timing_RP/timing_RP_2018.xml\""

task_prefix="timing_re_reco_2018"
task_suffix="_re_reco"

max_time="64800"

template_file="config/ctpps/2018/physics_fills/timing_re_reco_template.py"

Submit
