#!/bin/bash

source ctpps_block_submitter_new

runs=(
	# fill 7289
	324532
)

datasets=(
	"/EmptyBX/Run2018D-PromptReco-v2/AOD"
)

files_per_block="1"

output_dir="/eos/totem/data/offline/2018/450GeV/beta100/EmptyBX/version1"

geometry=""
alignment_files=""

task_prefix="re_reco_EmptyBX"
task_suffix="_re_reco_EmptyBX"

queue="8nh"

template_file="config/450GeV/beta100/re_reco_template.py"

SubmitBlocks
