#!/bin/bash

#----------------------------------------------------------------------------------------------------

# set defaults
test_only="y"
use_batch="n"
max_time="36000" # s

#----------------------------------------------------------------------------------------------------

function PrintUsage()
{
	echo "USAGE: submit <options> [config]"
	echo "OPTIONS:"
	echo "    -test               prepare jobs but do not execute"
	echo "    -run                prepare jobs and execute"
	echo "    -local              execute jobs locally"
	echo "    -batch              submit jobs to Condor"
	echo "    -submit             abbreviation of -run and -batch"
	echo "    -max-time <time>    use <time> as maxtime, implies -batch option"
}

#----------------------------------------------------------------------------------------------------

# load code
source "tb_code"

#----------------------------------------------------------------------------------------------------
# parse command line

while [ -n "$1" ]
do
	case "$1" in
		"-h" | "--help")
			PrintUsage
			exit 0
			;;

		"-test")
			test_only="y"
			;;

		"-run")
			test_only="n"
			;;

		"-local")
			use_batch="n"
			;;

		"-batch")
			use_batch="y"
			;;

		"-max-time")
			shift
			max_time="$1"
			use_batch="y"
			;;

		"-submit")
			test_only="n"
			use_batch="y"
			;;

		-*)
			echo "ERROR: unknown option '$1'."
			PrintUsage
			exit 1
			;;

		*)
			if [ -n "$input_config" ]
			then
				echo "ERROR: only one config can be used at at time."
				exit 1
			fi
			input_config="$1"
			;;

	esac

	shift
done

#----------------------------------------------------------------------------------------------------
# source config

if [ ! -f "$input_config" ]
then
	echo "ERROR: can't read config file '$input_config'."
	PrintUsage
	exit 1
fi

source "$input_config"
