#!/bin/bash

runs=(
	294736
	294737
	294739
	294741
)

datasets=(
	"/ZeroBias1/Run2017A-PromptReco-v1/AOD"
	"/ZeroBias2/Run2017A-PromptReco-v1/AOD"
	#"/ZeroBias3/Run2017A-PromptReco-v1/AOD"
	"/ZeroBias4/Run2017A-PromptReco-v1/AOD"
	#"/ZeroBias5/Run2017A-PromptReco-v1/AOD"
	#"/ZeroBias6/Run2017A-PromptReco-v1/AOD"
	#"/ZeroBias7/Run2017A-PromptReco-v1/AOD"
	#"/ZeroBias8/Run2017A-PromptReco-v1/AOD"
	#"/ZeroBias9/Run2017A-PromptReco-v1/AOD"
	#"/ZeroBias10/Run2017A-PromptReco-v1/AOD"
)

files_per_block="10"

output_dir="/eos/totem/data/ctpps/reconstruction/2017/alignment_run_May/version2-short"

geometry=""
alignment_files=""

task_prefix="re_reco"
task_suffix="_re_reco"

queue="8nh"

#----------------------------------------------------------------------------------------------------

template_file="config/ctpps/2017/alignment_run_May/re_reco_template.py"

#----------------------------------------------------------------------------------------------------

source ctpps_block_submitter
