#!/bin/bash

runs=(
	# crossing angle 150 urad
	294736
	294737
	294739

	# crossing angle 120 urad
	294741
)

# when run from DAS
##  source das_block_submitter
##  datasets=(
##  	"/ZeroBias1/Run2017A-PromptReco-v1/AOD"
##  	"/ZeroBias2/Run2017A-PromptReco-v1/AOD"
##  	"/ZeroBias3/Run2017A-PromptReco-v1/AOD"
##  	"/ZeroBias4/Run2017A-PromptReco-v1/AOD"
##  	"/ZeroBias5/Run2017A-PromptReco-v1/AOD"
##  	"/ZeroBias6/Run2017A-PromptReco-v1/AOD"
##  	"/ZeroBias7/Run2017A-PromptReco-v1/AOD"
##  	"/ZeroBias8/Run2017A-PromptReco-v1/AOD"
##  	"/ZeroBias9/Run2017A-PromptReco-v1/AOD"
##  	"/ZeroBias10/Run2017A-PromptReco-v1/AOD"
##  )
##  files_per_block="10"

# when run from EOS
source eos_block_submitter
input_dir="/eos/totem/data/ctpps/reconstruction/2017/alignment_run_May/AOD_skim"
input_filter_command="|grep _skim.root"
files_per_block="1"

output_dir="/eos/totem/data/ctpps/reconstruction/2017/alignment_run_May/version3"

geometry=""
alignment_files="\"CalibPPS/ESProducers/data/alignment/RPixGeometryCorrections-2017-2018.xml\""

task_prefix="re_reco_alig_2017_May"
task_suffix="_re_reco"

max_time="14400"

template_file="config/ctpps/2017/alignment_run_May/re_reco_template.py"

required_system="SLCern6"

SubmitBlocks
