#!/bin/bash

source json_submitter

streams=(
	#"SingleMuon"
	"DoubleEG"
	#"ZeroBias"
)

dataset_label="AOD"

dataset_exts=(
	"Run2017E-17Nov2017-v1/AOD"
	"Run2017F-17Nov2017-v1/AOD"
)

input_dir="/afs/cern.ch/work/j/jkaspar/analyses/ctpps/alignment/2017_postTS2/master/reduction/dataset_definition/json_selected"
input_filter_command="| grep xangle_1[2345]0"

#output_dir="/eos/totem/data/ctpps/reconstruction/2017/physics_runs/rec-hit-version1" # 10_6, with timing-geometry fix, new pixel internal alignment
output_dir="/eos/totem/data/ctpps/reconstruction/2017/physics_runs/rec-hit-version2" # 10_6, with timing-geometry fix, new pixel internal alignment; version1 disappeared from EOS

geometry=""

alignment_files="\"CalibPPS/ESProducers/data/alignment/RPixGeometryCorrections-2017-2018.xml\""

task_prefix="re_reco_2017_postTS2"
task_suffix="_re_reco"

max_time="64800"

template_file="config/ctpps/2017/physics_fills_postTS2/re_reco_template.py"

Submit
