#!/bin/bash

# what to optimise
sector="45"
z0="-210000"
rps="3,4,5,23,24,25"

# planes 4.4, 23.5
excludePlanes="1981939712,2023555072"

# event selection
minimumHitsPerProjectionPerRP=3
requireNumberOfUnits="2"
requireOverlap="False"
requireAtLeast3PotsInOverlap="True"

additionalAcceptedRPSets=""

# even number limit
#maxEvents="-1" # process all events
maxEvents="100000" # TODO

# iteration settings
iterations=4
#optimize=("s" "s" "sr")
optimize=("s")
maxResidualToSigma=(100 10 3)
chiSqPerNdfCut=(5000 50 5)
maxTrackAx=("0.5E-3")
maxTrackAy=("0.5E-3")

# constraint settings
constraintsType="standard" # nothing else enabled
constraintsLabel="std"
final_constraints_units="1,21"

# diagonistics
iterationsWithDiagnostics="2"

# input settings
reco_dir="/eos/totem/data/offline/2018/450GeV/beta11/ZeroBias/version1"

# geometry settings
geometry="data/geometry/2018_900GeV_beta11"

#initial_alignment=("data/alignment/2018_September/s+el/version1/45.xml")
initial_alignment=()

# output settings
subdir="tb,round1"
label=""  # for non-standard settings, e.g. ",test"

NewDataSet
tasks=(
	324579.1-45
	324579.46-99
)

SubmitTrackBasedAlignment
