#!/bin/bash

source json_submitter

streams=(
	"SingleMuon"
	"DoubleEG"
	"ZeroBias"
)

dataset_label="AOD"

dataset_exts=(
	"Run2017B-17Nov2017-v1/AOD"
	"Run2017C-17Nov2017-v1/AOD"
	"Run2017D-17Nov2017-v1/AOD"
)

input_dir="/afs/cern.ch/work/j/jkaspar/analyses/ctpps/alignment/2017_preTS2/master/reduction/dataset_definition/json_selected"
input_filter_command="| grep xangle_1[2345]0"

output_dir="/eos/totem/data/ctpps/reconstruction/2017/physics_runs/rec-hit-version1" # 10_6, with timing-geometry fix, new pixel internal alignment

geometry=""

alignment_files="\"CalibPPS/ESProducers/data/alignment/RPixGeometryCorrections-2017-2018.xml\""

task_prefix="re_reco_2017_preTS2"
task_suffix="_re_reco"

max_time="64800"

template_file="config/ctpps/2017/physics_fills_preTS2/re_reco_template.py"

Submit
