#!/bin/bash

source json_submitter

streams=(
	"SingleMuon"
	"DoubleEG"
	"ZeroBias"
)

dataset_exts=(
	"Run2017B-17Nov2017-v1/AOD"
	"Run2017C-17Nov2017-v1/AOD"
	"Run2017D-17Nov2017-v1/AOD"
)

input_dir="/afs/cern.ch/work/j/jkaspar/analyses/ctpps/alignment/2017_preTS2/master/reduction/dataset_definition/json_selected"
input_filter_command="| grep xangle_1[25]0"

output_dir="/eos/totem/data/ctpps/reconstruction/2017/preTS2_alignment_data/version5"

task_prefix="reduction_2017_preTS2"
task_suffix="_reduction"

max_time="14400"

template_file="config/ctpps/2017/physics_fills_preTS2/reduction_template.py"

Submit
