#!/bin/bash

source json_submitter

dataset_label="AOD"

input_dir="/afs/cern.ch/work/j/jkaspar/work/analyses/ctpps/alignment/2016_postTS2/reduction/dataset_definition/json"
input_filter_command=""

output_dir="/eos/cms/store/group/phys_pps/reconstruction/2016/physics_runs_post_TS2/version1" # with CMSSW_10_6_1, no alignment

geometry="" # not used
alignment_files="" # not used

task_prefix="re_reco_2016_postTS2"
task_suffix="_re_reco"

max_time="64800"

required_system="CentOS7"

#----------------------------------------------------------------------------------------------------

template_file="config/ctpps/2016/physics_fills_postTS2/re_reco_template_old.py"

streams=(
	"Charmonium"
	"DoubleEG"
	"DoubleMuon"
	"DoubleMuonLowMass"
	"SingleMuon"
)

dataset_exts=(
	"Run2016H-PromptReco-v2/AOD"
)

Submit

#----------------------------------------------------------------------------------------------------

template_file="config/ctpps/2016/physics_fills_postTS2/re_reco_template.py"

streams=(
	"BTagCSV"
	"JetHT"
	"SingleElectron"
	"Tau"
	"ZeroBias"
)

dataset_exts=(
	"Run2016H-07Aug17-v1/AOD"
)

Submit
