#!/bin/bash

runs=(
	"10190"
	#"10191"
	"10192"
	#"10193"
	"10194"
	#"10195"
	"10196"
	#"10197"
	"10198"
	#"10199"
	"10200"
	#"10201"
	"10202"
	#"10203"
	"10204"
	#"10205"
	"10206"
)

input_dir="/eos/totem/data/rawdata/2016"
input_filter_command="| grep run_\$run | grep .srs"

files_per_block="10"

template_file="config/13TeV/2500m/reco_template.py"

mapping="\"TotemCondFormats/DAQInformation/data/rp_210new_220far.xml\""

geometry="2016_09_20_fill5313"

alignment_files="'TotemAlignment/RPData/LHC/2016_09_20_fill5313/version1/sr+el/45.xml', 'TotemAlignment/RPData/LHC/2016_09_20_fill5313/version1/sr+el/56.xml'"

#output_dir="/eos/totem/user/j/jkaspar/reco/alignment_none"
#output_dir="/eos/totem/user/j/jkaspar/reco/alignment_sr"
output_dir="/eos/totem/data/offline/2016/2500m/version2"

task_prefix="$geometry/reco"
task_suffix="_reco"

queue="8nh"

#----------------------------------------------------------------------------------------------------

source standard_block_submitter
