#!/bin/bash

runs=(
	"10208"
	"10209"
	"10210"
	#"10211"
	"10212"
	#"10213"
	"10214"
	#"10215"
	"10216"
	#"10217"
	"10218"
	#"10219"
	"10220"
	#"10221"
	"10222"
	#"10223"
	"10224"
)

input_dir="/eos/totem/data/rawdata/2016"
input_filter_command="| grep run_\$run | grep .srs"

files_per_block="10"

template_file="config/13TeV/2500m/reco_template.py"

mapping="\"TotemCondFormats/DAQInformation/data/rp_210new_220far.xml\""

geometry="2016_09_20_fill5314"

alignment_files="'TotemAlignment/RPData/LHC/2016_09_20_fill5314/version1/sr+el/45.xml', 'TotemAlignment/RPData/LHC/2016_09_20_fill5314/version1/sr+el/56.xml'"

#output_dir="/eos/totem/user/j/jkaspar/reco/alignment_none"
#output_dir="/eos/totem/user/j/jkaspar/reco/alignment_sr"
output_dir="/eos/totem/data/offline/2016/2500m/version1"

task_prefix="$geometry/reco"
task_suffix="_reco"

queue="8nh"

#----------------------------------------------------------------------------------------------------

source standard_block_submitter
