#!/bin/bash

runs=(
	"10225"
	#"10226"
	"10227"
	#"10228"
	"10229"
	#"10230"
	"10231"
	#"10232"
	"10233"
	"10234"
	#"10235"
	"10236"
	#"10237"
	"10238"
	#"10239"
	"10240"
	#"10241"
	"10242"
	"10243"
	#"10244"
	"10245"
	"10246"
	"10248"
	"10249"
	"10250"
	#"10251"
	"10252"
	#"10253"
	"10254"
	#"10255"
	"10256"
	#"10257"
	"10258"
	#"10259"
	"10260"
	#"10261"
	"10262"
	#"10263"
	"10264"
	#"10265"
	"10266"
	#"10267"
	"10268"
	#"10269"
	"10270"
	#"10271"
	"10272"
)

input_dir="/eos/totem/data/rawdata/2016"
input_filter_command="| grep run_\$run | grep .srs"

files_per_block="10"

template_file="config/13TeV/2500m/reco_template.py"

mapping="\"TotemCondFormats/DAQInformation/data/rp_210new_220far.xml\""

geometry="2016_09_21_fill5317"

alignment_files="'TotemAlignment/RPData/LHC/2016_09_21_fill5317/version1/sr+el/45.xml', 'TotemAlignment/RPData/LHC/2016_09_21_fill5317/version1/sr+el/56.xml'"

#output_dir="/eos/totem/user/j/jkaspar/reco/alignment_none"
#output_dir="/eos/totem/user/j/jkaspar/reco/alignment_sr"
output_dir="/eos/totem/data/offline/2016/2500m/version2"

task_prefix="$geometry/reco"
task_suffix="_reco"

queue="8nh"

#----------------------------------------------------------------------------------------------------

source standard_block_submitter
