#!/bin/bash

runs=(
	318546
	318547
	318548
	318549
	318550
	318551
)

datasets=(
	"/TOTEM3/Run2018B-v1/RAW"
)

files_per_block="1"

output_dir="/eos/totem/user/j/jkaspar/reco/2018_90m/TOTEM3/version2"

alignment_files=""

task_prefix="reco_TOTEM3"
task_suffix="_reco"

queue="8nh"

#----------------------------------------------------------------------------------------------------

template_file="config/2018_90m/alignment_run/template_reco.py"

#----------------------------------------------------------------------------------------------------

source ctpps_block_submitter
