#!/bin/bash

source das_block_submitter

runs=(
	303719

	303790
	303793
	303794
	303795
)

datasets=(
	"/ZeroBiasPD01/Run2017E-PromptReco-v1/AOD"
	"/ZeroBiasPD02/Run2017E-PromptReco-v1/AOD"
	"/ZeroBiasPD03/Run2017E-PromptReco-v1/AOD"
	"/ZeroBiasPD04/Run2017E-PromptReco-v1/AOD"
	"/ZeroBiasPD05/Run2017E-PromptReco-v1/AOD"
	"/ZeroBiasPD06/Run2017E-PromptReco-v1/AOD"
	"/ZeroBiasPD07/Run2017E-PromptReco-v1/AOD"
	"/ZeroBiasPD08/Run2017E-PromptReco-v1/AOD"
	"/ZeroBiasPD09/Run2017E-PromptReco-v1/AOD"
	"/ZeroBiasPD10/Run2017E-PromptReco-v1/AOD"
)

files_per_block="10"

output_dir="/eos/totem/data/ctpps/reconstruction/2017/postTS2_alignment_data/version1-early-fills"

alignment_files=""

task_prefix="re_reco"
task_suffix="_re_reco"

max_time="14400"

#----------------------------------------------------------------------------------------------------

template_file="config/ctpps/2017/phys_postTS2/template_re_reco.py"

#----------------------------------------------------------------------------------------------------

SubmitBlocks
