#!/bin/bash

runs=(
	303652
	303658
	303665
)

datasets=(
	"/ZeroBias1/Run2017E-PromptReco-v1/AOD"
	"/ZeroBias2/Run2017E-PromptReco-v1/AOD"
	"/ZeroBias3/Run2017E-PromptReco-v1/AOD"
	"/ZeroBias4/Run2017E-PromptReco-v1/AOD"
	"/ZeroBias5/Run2017E-PromptReco-v1/AOD"
	"/ZeroBias6/Run2017E-PromptReco-v1/AOD"
	"/ZeroBias7/Run2017E-PromptReco-v1/AOD"
	"/ZeroBias8/Run2017E-PromptReco-v1/AOD"
	"/ZeroBias9/Run2017E-PromptReco-v1/AOD"
	"/ZeroBias10/Run2017E-PromptReco-v1/AOD"
)

files_per_block="10"

output_dir="/eos/totem/data/ctpps/reconstruction/2017/alignment_run_September/version2"

alignment_files="\"Alignment/CTPPS/data/2017_postTS2/strip_packages_rotation.xml\""

task_prefix="re_reco"
task_suffix="_re_reco"

queue="8nh"

#----------------------------------------------------------------------------------------------------

template_file="config/ctpps/2017/alignment_run_September/template_re_reco.py"

#----------------------------------------------------------------------------------------------------

source ctpps_block_submitter
