#!/bin/bash

source das_block_submitter

datasets=(
	"/ZeroBias1/Commissioning2018-26Apr2018-v1/AOD"
	"/ZeroBias2/Commissioning2018-26Apr2018-v1/AOD"
	"/ZeroBias3/Commissioning2018-26Apr2018-v1/AOD"
	"/ZeroBias4/Commissioning2018-26Apr2018-v1/AOD"
	"/ZeroBias5/Commissioning2018-26Apr2018-v1/AOD"
	"/ZeroBias6/Commissioning2018-26Apr2018-v1/AOD"
	"/ZeroBias7/Commissioning2018-26Apr2018-v1/AOD"
	"/ZeroBias8/Commissioning2018-26Apr2018-v1/AOD"
	"/ZeroBias9/Commissioning2018-26Apr2018-v1/AOD"
	"/ZeroBias10/Commissioning2018-26Apr2018-v1/AOD"
)

files_per_block="5"

output_dir="/eos/totem/data/ctpps/reconstruction/2018/alignment_run_April/version5"

geometry="" # not used

task_prefix="re_reco"
task_suffix="_re_reco"

max_time="14400"

template_file="config/ctpps/2018/alignment_run_April/template_re_reco.py"

#----------------------------------------------------------------------------------------------------

#xangle=160, beta*=0.3
runs=(
	314247
)

alignment_dir="alignment/2018_April/s/version2/xangle-160-beta-30"
alignment_files="\"$alignment_dir/45.xml\", \"$alignment_dir/56.xml\""

SubmitBlocks

#xangle=131, beta*=0.3
runs=(
	314248
	314250
	314255
	314267
)

alignment_dir="alignment/2018_April/s/version2/xangle-131-beta-30"
alignment_files="\"$alignment_dir/45.xml\", \"$alignment_dir/56.xml\""

SubmitBlocks

#xangle=130, beta*=0.3
runs=(
	314269
	314270
	314272
	314273
)

alignment_dir="alignment/2018_April/s/version2/xangle-130-beta-30"
alignment_files="\"$alignment_dir/45.xml\", \"$alignment_dir/56.xml\""

SubmitBlocks

#xangle=130, beta*=0.25
runs=(
	314274
	314275
	314276
)

alignment_dir="alignment/2018_April/s/version2/xangle-130-beta-25"
alignment_files="\"$alignment_dir/45.xml\", \"$alignment_dir/56.xml\""

SubmitBlocks
