#!/bin/bash

runs=(
	#xangle=160, beta*=0.3
	314247

	#xangle=131, beta*=0.3
	314248
	314250
	314255
	314267

	#xangle=130, beta*=0.3
	314269
	314270
	314272
	314273

	#xangle=130, beta*=0.25
	314274
	314275
	314276
)

datasets=(
	"/Totem1/Commissioning2018-PromptReco-v1/AOD"
	#"/ZeroBias1/Commissioning2018-26Apr2018-v1/AOD"
)

files_per_block="1"

output_dir="/eos/totem/data/ctpps/reconstruction/2018/alignment_run_April/version1"

alignment_files=""

#alignment_dir="alignment/2018_postTS2/s+el/version1"
#alignment_files="\"$alignment_dir/45.xml\", \"$alignment_dir/56.xml\""

task_prefix="re_reco"
task_suffix="_re_reco"

queue="8nh"

#----------------------------------------------------------------------------------------------------

template_file="config/ctpps/2018/alignment_run_April/template_re_reco.py"

#----------------------------------------------------------------------------------------------------

source ctpps_block_submitter
