#!/bin/bash

source das_block_submitter

datasets=(
	"/ZeroBias1/Commissioning2018-26Apr2018-v1/AOD"
	"/ZeroBias2/Commissioning2018-26Apr2018-v1/AOD"
	"/ZeroBias3/Commissioning2018-26Apr2018-v1/AOD"
	"/ZeroBias4/Commissioning2018-26Apr2018-v1/AOD"
	"/ZeroBias5/Commissioning2018-26Apr2018-v1/AOD"
	"/ZeroBias6/Commissioning2018-26Apr2018-v1/AOD"
	"/ZeroBias7/Commissioning2018-26Apr2018-v1/AOD"
	"/ZeroBias8/Commissioning2018-26Apr2018-v1/AOD"
	"/ZeroBias9/Commissioning2018-26Apr2018-v1/AOD"
	"/ZeroBias10/Commissioning2018-26Apr2018-v1/AOD"
)

files_per_block="5"

output_dir="/eos/totem/data/ctpps/reconstruction/2018/alignment_run_April/AOD_skim"

geometry="" # not used

alignment_files="" # not used

task_prefix="skim"
task_suffix="_skim"

max_time="14400"

template_file="config/ctpps/2018/alignment_run_April/skim_template.py"

required_system="SLCern6"

#----------------------------------------------------------------------------------------------------

#xangle=160, beta*=0.3
runs=(
	314247
)

SubmitBlocks

#xangle=131, beta*=0.3
runs=(
	314248
	314250
	314255
	314267
)

SubmitBlocks

#xangle=130, beta*=0.3
runs=(
	314269
	314270
	314272
	314273
)

SubmitBlocks

#xangle=130, beta*=0.25
runs=(
	314274
	314275
	314276
)

SubmitBlocks
