#!/bin/bash

#----------------------------------------------------------------------------------------------------

function FlushBlock()
{
	input_blocks+=("$buffer")
	input_block_labels+=("${task_prefix}/fill_$fill/$dataset_tag/$block_idx")
	input_block_runs+=("")
	input_block_ls_selections+=("$ls_sel")
	input_block_output_tags+=("fill_${fill}_${dataset_tag}.${block_idx}${task_suffix}")
	input_block_lv1Bits+=("$lv1Bits")
	input_block_geometries+=("$geometry")
	input_block_alignment_files+=("$alignment_files")
	input_block_template_files+=("$template_file")
	input_block_output_dirs+=("$output_dir")

	buffer=""
	let buffer_size=0
	let block_idx+=1
}

#----------------------------------------------------------------------------------------------------

function SubmitBlocks()
{
	# process input
	for fill_spec in ${fills[*]}
	do
		fill=${fill_spec%%-*}
		fill_spec=${fill_spec#*-}
		run_min=${fill_spec%%-*}
		run_max=${fill_spec#*-}

		ls_sel="\"${run_min}:1-${run_max}:max\""

		for dataset in ${datasets[*]}
		do
			dataset_tag=${dataset#*/}
			dataset_tag=${dataset_tag%%/*}

			buffer=""
			buffer_size="0"
			block_idx="0"

			echo "* querying input for runs $run_min - $run_max, dataset $dataset_tag"

			for file in `dasgoclient --limit=0 --query "file dataset=$dataset run in [$run_min, $run_max]"`
			do
				buffer="$buffer $file"
				let buffer_size+=1
			
				if [ "$buffer_size" -ge "$files_per_block" ]
				then
					FlushBlock
				fi
			done
			
			if [ "$buffer_size" -gt "0" ]
			then
				FlushBlock
			fi
		done
	done
}

#----------------------------------------------------------------------------------------------------

files_per_block="100"

output_dir="/eos/totem/data/ctpps/reconstruction/2016/preTS2_alignment_data/version1"

geometry="" # not used

queue="8nh"

template_file="config/ctpps/2016/phys_preTS2/template_reduction.py"

alignment_files=""


#----------------------------------------------------------------------------------------------------

task_prefix="reduction_margin"
task_suffix="_reduction_margin"

# 2016B, with margin

datasets=(
	"/DoubleEG/Run2016B-07Aug17_ver2-v2/MINIAOD"
	"/SingleMuon/Run2016B-07Aug17_ver2-v1/MINIAOD"
	"/ZeroBias/Run2016B-07Aug17_ver2-v1/MINIAOD"
)

fills=(
	"4947-273725-273730"
	"4953-274094-274094"
	"4961-274198-274200"
	"4964-274240-274241"
	"4976-274282-274286"
)

SubmitBlocks

task_prefix="reduction"
task_suffix="_reduction"

# 2016B, without margin

fills=(
	"4964-274244-274244"
	"4985-274387-274388"
	"4988-274420-274422"
	"4990-274440-274443"
	"5005-274954-274959"
	"5013-274966-274971"
	"5017-274998-275001"
	"5020-275059-275074"
	"5021-275124-275125"
	"5024-275282-275293"
	"5026-275309-275311"
	"5027-275319-275338"
	"5028-275344-275345"
	"5029-275370-275371"
	"5030-275375-275376"
)

SubmitBlocks

#----------------------------------------------------------------------------------------------------

# 2016C, without margin
datasets=(
	"/DoubleEG/Run2016C-07Aug17-v1/MINIAOD"
	"/SingleMuon/Run2016C-07Aug17-v1/MINIAOD"
	"/ZeroBias/Run2016C-07Aug17-v1/MINIAOD"
)

fills=(
	"5038-275656-275659"
	"5043-275757-275783"
	"5045-275828-275847"
	"5048-275886-275890"
	"5052-275911-275931"
)

SubmitBlocks

#----------------------------------------------------------------------------------------------------

#2016G, without margin
datasets=(
	"/DoubleEG/Run2016G-07Aug17-v1/MINIAOD"
	"/SingleMuon/Run2016G-07Aug17-v1/MINIAOD"
	"/ZeroBias/Run2016G-07Aug17-v1/MINIAOD"
)

fills=(
	"5261-279760-279767"
	"5264-279794-279794"
	"5265-279823-279823"
	"5266-279841-279841"
	"5267-279844-279865"
	"5274-279931-279931"
	"5275-279966-279966"
	"5276-279975-279975"
	"5277-279993-280024"
	"5279-280187-280194"
	"5287-280327-280364"
	"5288-280383-280385"
)

SubmitBlocks
