#!/bin/bash

source eos_block_submitter

runs=(
	10332
	10331
	10329
	10328
	10327
	10326
	10325
	10324
	10322
	10323
)

files_per_block="1"

input_dir="/eos/totem/data/rawdata/2016"
input_filter_command="|grep .srs"

#output_dir="/eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/digi_version1"
output_dir="/eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/digi_version2" # set run number from file name, store TOTEM trigger data

geometry="" # not used
alignment_files="" # not used

max_time="82800"

task_prefix="rawToDigi_2016_postTS2"
task_suffix="_rawToDigi"

template_file="config/ctpps/2016/alignment_run_September/rawToDigi_template.py"

required_system="SLCern6"

SubmitBlocks
