#!/bin/bash

runs=(
	"9843"
	"9844"
	"9845"
)

# TODO: update
input_dir="/eos/totem/data/offline/2016/90m_5sigma/version-pilot"

input_filter_command="| grep run_\$run | grep _reco.root"

files_per_block="1"

template_file="config/13TeV/90m_5sigma/ntuple_template_T2_RP_cfg.py"

mapping="" # irrelevant

alignment_files="" #irrelevant

# TODO: update
output_dir="/eos/totem/data/offline/2016/90m_5sigma/version-pilot"

task_prefix="$geometry/ntuple"
task_suffix="_ntuple"

queue="8nh"

#----------------------------------------------------------------------------------------------------

source standard_block_submitter
