#!/bin/bash

runs=(
	"9836"
	"9838"
	"9840"
	"9841"
)

input_dir="/eos/totem/data/offline/2015/90m_5sigma/version1"

input_filter_command="| grep run_\$run | grep _reco.root"

files_per_block="1"

template_file="config/13TeV/90m_5sigma/ntuple_template_T1_T2_RP_cfg.py"

mapping="" # irrelevant

geometry="2015_10_13_fill4489"

alignment_files="" #irrelevant

output_dir="/eos/totem/data/offline/2015/90m_5sigma/version1"

task_prefix="$geometry/ntuple"
task_suffix="_ntuple"

queue="1nd"

#----------------------------------------------------------------------------------------------------

source standard_block_submitter
