#!/bin/bash

# what to optimise
sector="45"
z0="-210000"
rps="3,4,5,23,24,25"

# planes 4.4, 23.5
excludePlanes="1981939712,2023555072"

# event selection
minimumHitsPerProjectionPerRP=3
requireNumberOfUnits="2"
requireOverlap="False"
requireAtLeast3PotsInOverlap="True"

additionalAcceptedRPSets=""

# even number limit
#maxEvents="-1" # process all events
maxEvents="200000" # TODO

# iteration settings
iterations=4
#optimize=("s" "s" "sr")
optimize=("s")
maxResidualToSigma=(10 3)
chiSqPerNdfCut=(50 5)
maxTrackAx=("0.5E-3")
maxTrackAy=("0.5E-3")

# constraint settings
constraintsType="standard" # nothing else enabled
constraintsLabel="std"
final_constraints_units="1,21"

# diagonistics
iterationsWithDiagnostics="0"

# input settings
reco_dir="/eos/totem/data/ctpps/reconstruction/2018/alignment_run_September/AOD_skim"

# geometry settings
geometry="data/geometry/2018_September/2018_09_22_fill7206"

initial_alignment=("data/alignment/2018_September/s+el/version1/45.xml")

# output settings
subdir="tb,round3"
label=""  # for non-standard settings, e.g. ",test"

NewDataSet
tasks=(
	# xangle=130, beta*=0.27
	323311.1-91
	323311.92-182
	323312.1-60
	323312.61-120

	# xangle=130, beta*=0.25
	323316.1-100
	323316.101-200
	323316.201-317
)

SubmitTrackBasedAlignment
