#!/bin/bash

runs=(
	315922
	315934
	315956
)

datasets=(
	"/Totem1/Run2018A-PromptReco-v1/AOD"
)

files_per_block="1"

output_dir="/eos/totem/data/offline/2018/450GeV/test_2018_05_08/version2"

alignment_files=""

task_prefix="re_reco2"
task_suffix="_re_reco"

queue="8nh"

#----------------------------------------------------------------------------------------------------

template_file="config/450GeV/template_re_reco.py"

#----------------------------------------------------------------------------------------------------

source ctpps_block_submitter
