#!/bin/bash

source das_block_submitter

datasets=(
	"/ZeroBias1/Run2018D-PromptReco-v2/AOD"
	"/ZeroBias2/Run2018D-PromptReco-v2/AOD"
	"/ZeroBias3/Run2018D-PromptReco-v2/AOD"
	"/ZeroBias4/Run2018D-PromptReco-v2/AOD"
	"/ZeroBias5/Run2018D-PromptReco-v2/AOD"
	"/ZeroBias6/Run2018D-PromptReco-v2/AOD"
	"/ZeroBias7/Run2018D-PromptReco-v2/AOD"
	"/ZeroBias8/Run2018D-PromptReco-v2/AOD"
	"/ZeroBias9/Run2018D-PromptReco-v2/AOD"
	"/ZeroBias10/Run2018D-PromptReco-v2/AOD"
)

files_per_block="5"

output_dir="/eos/totem/data/ctpps/reconstruction/2018/alignment_run_September/AOD_skim"

geometry=""

alignment_files=""

task_prefix="skim"
task_suffix="_skim"

max_time="14400"

template_file="config/ctpps/2018/alignment_run_September/skim_template.py"

required_system="SLCern6"

#----------------------------------------------------------------------------------------------------

#xangle=130, beta*=0.27
runs=(
	323311
	323312
)

SubmitBlocks

#xangle=130, beta*=0.25
runs=(
	323316
)

SubmitBlocks
