#!/bin/bash

#----------------------------------------------------------------------------------------------------

function SubmitTBAForAllStations()
{
	if [ "$submit_sector_45" == "y" ]
	then
		sector="45"; z0="-217000"; rps="$rps_45"
		SubmitTrackBasedAlignment
	fi

	if [ "$submit_sector_56" == "y" ]
	then
		sector="56"; z0="+217000"; rps="$rps_56"
		SubmitTrackBasedAlignment
	fi
}

#----------------------------------------------------------------------------------------------------

# what to optimise
submit_sector_45="y"
rps_45="0,1,2,3,4,5"

submit_sector_56="n"
rps_56=""

#   * some runs have: 50, 51, 52 and 53

#   * 32, 37 and 29 may have sufficient signal
#excludePlanes="29,32,37,44,50,51,52,53"

# there are other planes with problems
#     32, 37 and 29: one VFAT only
#     50, 51, 52 and 53: full fiber, but only sometimes
excludePlanes="44"

# event selection
minimumHitsPerProjectionPerRP=3
requireNumberOfUnits="2"
requireOverlap="False"
requireAtLeast3PotsInOverlap="True"

additionalAcceptedRPSets=""

# even number limit
maxEvents="0" # process all events
#maxEvents="10000" # TODO remove
maxEvents="20000" # TODO remove

# iteration settings
iterations=5
optimize=("s" "s" "sr")
maxResidualToSigma=(100 10 10 3)
chiSqPerNdfCut=(5000 50 50 5)
maxTrackAx=("0.2E-3")
maxTrackAy=("0.2E-3")

# constraint settings
constraintsType="final"
constraintsLabel="fin"
final_constraints_units="0, 1"

useExtendedConstraints=("True")
useZeroThetaRotZConstraint="True"
useEqualMeanUMeanVRotZConstraint="False"

# diagonistics
iterationsWithDiagnostics="0"
iterationsWithDiagnostics="4" # TODO

# input settings
reco_dir="/eos/totem/user/j/jkaspar/reco/alignment_none"
#reco_dir="/eos/totem/user/j/jkaspar/reco/alignment_sr_el"

# geometry settings
geometry="2016_09_24_fill5322"

#initial_alignment=(
#	"/afs/cern.ch/work/j/jkaspar/software/offline/704/src/TotemAlignment/RPData/LHC/2016_04_20_fill4828/version1/sr+el/45.xml"
#	"/afs/cern.ch/work/j/jkaspar/software/offline/704/src/TotemAlignment/RPData/LHC/2016_04_20_fill4828/version1/sr+el/56.xml"
#)

# output settings
subdir="tb,round1"
label=""  # for non-standard settings
label=",diag"  # TODO

NewDataSet
tasks=(
# TODO
#	"10322"
#	"10324"
#	"10325"
#	"10326"
#	"10327" # troubles to run with all planes in RP 5
	"10328"
#	"10329"
#	"10331"
	"10332"
)
SubmitTBAForAllStations
