#!/bin/bash

runs=(
# TODO uncomment
	"10322"
#	"10324"
#	"10325"
#	"10326"
#	"10327"
#	"10328"
#	"10329"
#	"10331"
#	"10332"
)

#----------------------------------------------------------------------------------------------------

input_dir="/eos/totem/user/j/jkaspar/reco/alignment_sr"
input_filter_command="| grep run_\$run | grep _reco.root"

files_per_block="10"

template_file="config/ctpps/ntuple_template.py"

mapping="" # irrelevant

geometry="2016_09_24_fill5322"

alignment_files="" # irrelevant

output_dir="/eos/totem/user/j/jkaspar/reco/alignment_sr"

task_prefix="$geometry/ntuple"
task_suffix="_ntuple"

queue="8nh"

#----------------------------------------------------------------------------------------------------

source standard_block_submitter
