#!/bin/bash

# what to optimise
sector="45"
z0="-210000"
rps="0,1,2,3,4,5"

# trouble some planes
#   * some runs have: 50, 51, 52 and 53
#   * 32, 37 and 29 may have sufficient signal
# there are other planes with problems
#     32, 37 and 29: one VFAT only
#     50, 51, 52 and 53: full fiber, but only sometimes
#
# exclude planes 4.4
excludePlanes="1981939712"

# event selection
minimumHitsPerProjectionPerRP=3
requireNumberOfUnits="2"
requireOverlap="False"
requireAtLeast3PotsInOverlap="True"

additionalAcceptedRPSets=""

# even number limit
maxEvents="-1" # process all events
#maxEvents="40000"

# iteration settings
iterations=4
#optimize=("s" "s" "sr")
optimize=("s")
maxResidualToSigma=(15 10 3)
#maxResidualToSigma=(10 3)
chiSqPerNdfCut=(100 50 5)
#chiSqPerNdfCut=(50 5)
maxTrackAx=("0.5E-3")
maxTrackAy=("0.5E-3")

# constraint settings
constraintsType="final"
constraintsLabel="fin"
final_constraints_units="0, 1"

# diagonistics
iterationsWithDiagnostics="0"

# input settings
reco_dir="/eos/cms/store/group/phys_pps/reconstruction/2016/alignment_run_September/version1-test2"

# geometry settings
geometry="data/geometry/2016_September/2016_09_24_fill5322"

initial_alignment=("data/alignment/2016_September/init/45.xml")

# output settings
subdir="tb,round1"
label=""  # for non-standard settings, e.g. ",test"

NewDataSet
tasks=(
	"10322"
	"10324"
	"10325"
	"10326"
	"10327"
	"10328"
	"10329"
	"10331"
	"10332"
)

SubmitTrackBasedAlignment
