#!/bin/bash

#----------------------------------------------------------------------------------------------------
# defaults

test_only="y"
use_batch="n"
max_time="14400" # s
required_system="CentOS7"

#----------------------------------------------------------------------------------------------------

function PrintUsage()
{
	echo "USAGE: submit <options> [config]"
	echo "OPTIONS:"
	echo "    -test             prepare jobs but do not execute"
	echo "    -run              prepare jobs and execute"
	echo "    -local            execute jobs locally"
	echo "    -batch, -batch    submit jobs to BATCH"
	echo "    -submit           abbreviation of -run and -batch"
	echo "    -maxtime <v>      set maxtime of the BATCH job"
	echo "    -system <spec>    set system requirements (SLCern6, CentOS7, ...)"
}

#----------------------------------------------------------------------------------------------------
# load code
source "tb_code"

#----------------------------------------------------------------------------------------------------
# parse command line

while [ -n "$1" ]
do
	case "$1" in
		"-h" | "--help")
			PrintUsage
			exit 0
			;;

		"-test")
			test_only="y"
			;;

		"-run")
			test_only="n"
			;;

		"-local")
			use_batch="n"
			;;

		"-batch")
			use_batch="y"
			;;

		"-maxtime")
			shift
			max_time="$1"
			;;

        "-system")
			shift
            required_system="$1"
            ;;

		"-submit")
			test_only="n"
			use_batch="y"
			;;

		-*)
			echo "ERROR: unknown option '$1'."
			PrintUsage
			exit 1
			;;

		*)
			if [ -n "$input_config" ]
			then
				echo "ERROR: only one config can be used at at time."
				exit 1
			fi
			input_config="$1"
			;;

	esac

	shift
done

#----------------------------------------------------------------------------------------------------
# source config

if [ ! -f "$input_config" ]
then
	echo "ERROR: can't read config file '$input_config'."
	PrintUsage
	exit 1
fi

source "$input_config"
