#!/bin/bash

source das_block_submitter

runs=(
	# fill 7301
	324575
	324576
	
	# fill 7302
	324578
	324579
	324580
	324581
)

datasets=(
	"/Totem1/Run2018D-PromptReco-v2/AOD"
)

files_per_block="1"

output_dir="/eos/totem/data/offline/2018/450GeV/beta11/Totem1/version4"

geometry="geometry/2018_900GeV_beta11/RP_Dist_Beam_Cent.xml"

alignment_dir="alignment/2018_900GeV_beta11/sr/version1"
alignment_files="\"$alignment_dir/45.xml\", \"$alignment_dir/56.xml\""

task_prefix="re_reco_Totem1"
task_suffix="_re_reco_Totem1"

queue="8nh"

template_file="config/450GeV/beta11/re_reco_template.py"

SubmitBlocks
