#!/bin/bash

# when run from DAS
#source das_block_submitter
#datasets=("/Totem1/Run2018D-PromptReco-v2/AOD")

# when run from EOS
source eos_block_submitter
input_dir="/eos/totem/data/offline/2018/450GeV/beta11/Totem1/version3"
input_filter_command="|grep _re_reco_Totem1.root"

runs=(
	# fill 7301
	324575
	324576
	
	# fill 7302
	324578
	324579
	324580
	324581
)

files_per_block="1"

#output_dir="/eos/totem/data/offline/2018/450GeV/beta11/Totem1/version4" # with alignment sr/version1
#output_dir="/eos/totem/data/offline/2018/450GeV/beta11/Totem1/version5" # with alignment sr/version2

geometry="geometry/2018_900GeV_beta11/RP_Dist_Beam_Cent.xml"

alignment_dir="alignment/2018_900GeV_beta11/sr/version2"
alignment_files="\"$alignment_dir/45.xml\", \"$alignment_dir/56.xml\""

task_prefix="re_reco_Totem1"
task_suffix="_re_reco_Totem1"

max_time="28800"

template_file="config/450GeV/beta11/re_reco_template.py"

SubmitBlocks
