#!/bin/bash

source ctpps_block_submitter_new

runs=(
	# fill 7301
	#324575
	#324576
	
	# fill 7302
	#324578
	324579
	#324580
	#324581
)

datasets=(
	"/ZeroBias1/Run2018D-PromptReco-v2/AOD"
	"/ZeroBias2/Run2018D-PromptReco-v2/AOD"
	"/ZeroBias3/Run2018D-PromptReco-v2/AOD"
	"/ZeroBias4/Run2018D-PromptReco-v2/AOD"
	"/ZeroBias5/Run2018D-PromptReco-v2/AOD"
	"/ZeroBias6/Run2018D-PromptReco-v2/AOD"
	"/ZeroBias7/Run2018D-PromptReco-v2/AOD"
	"/ZeroBias8/Run2018D-PromptReco-v2/AOD"
	"/ZeroBias9/Run2018D-PromptReco-v2/AOD"
	"/ZeroBias10/Run2018D-PromptReco-v2/AOD"
)

files_per_block="1"

output_dir="/eos/totem/data/offline/2018/450GeV/beta11/ZeroBias/version1"

geometry="data/geometry/2018_900GeV_beta11/RP_Dist_Beam_Cent.xml"
alignment_files=""

task_prefix="re_reco_ZeroBias"
task_suffix="_re_reco_ZeroBias"

queue="8nh"

template_file="config/450GeV/beta11/re_reco_template.py"

SubmitBlocks
