#!/bin/bash

source das_block_submitter

runs=(
	# fill 7301
	324575
	324576
	
	# fill 7302
	324578
	324579
	324580
	324581
)

datasets=(
	"/Totem1/Run2018D-v1/RAW"
)

#datasets=(
#	"/ZeroBias1/Run2018D-v1/RAW"
#	"/ZeroBias2/Run2018D-v1/RAW"
#	"/ZeroBias3/Run2018D-v1/RAW"
#	"/ZeroBias4/Run2018D-v1/RAW"
#	"/ZeroBias5/Run2018D-v1/RAW"
#	"/ZeroBias6/Run2018D-v1/RAW"
#	"/ZeroBias7/Run2018D-v1/RAW"
#	"/ZeroBias8/Run2018D-v1/RAW"
#	"/ZeroBias9/Run2018D-v1/RAW"
#	"/ZeroBias10/Run2018D-v1/RAW"
#)

files_per_block="1"

output_dir="/eos/totem/data/offline/2018/450GeV/beta11/Totem1/version1"

geometry=""
alignment_files=""

task_prefix="reco_Totem1"
task_suffix="_reco_Totem1"

queue="8nh"

template_file="config/450GeV/beta11/reco_template.py"

SubmitBlocks
