#!/bin/bash

# what to optimise
sector="56"
z0="+210000"
rps="103,104,105,123,124,125"

# nothing to exclude
excludePlanes=""

# event selection
minimumHitsPerProjectionPerRP=3
requireNumberOfUnits="2"
requireOverlap="False"
requireAtLeast3PotsInOverlap="True"

additionalAcceptedRPSets=""

# even number limit
#maxEvents="-1" # process all events
maxEvents="10000"

# iteration settings
iterations=4
#optimize=("s" "s" "sr")
optimize=("s")
maxResidualToSigma=(10 3)
chiSqPerNdfCut=(50 5)
maxTrackAx=("0.5E-3")
maxTrackAy=("0.5E-3")

# constraint settings
constraintsType="standard" # nothing else enabled
constraintsLabel="std"
final_constraints_units="101,121"

# diagonistics
iterationsWithDiagnostics="0"

# input settings
#reco_dir="/eos/totem/data/ctpps/reconstruction/2018/alignment_run_April/AOD_skim"
reco_dir="/eos/cms/store/group/phys_pps/reconstruction/2018/alignment_run_April/version7"

# geometry settings
geometry="data/geometry/2018_April/2018_04_13_fill6554"

#initial_alignment=("data/alignment/2018_April/s+el/version1/56.xml")
initial_alignment=("data/alignment/2018_April/s+el/version3/xangle-160-beta-30/56.xml")

# output settings
subdir="tb,round4-check"
label=""  # for non-standard settings, e.g. ",test"

NewDataSet
tasks=(
	# xangle-160-beta-30
	#314247
	314247.1-20
	314247.21-40
	314247.41-61

	# xangle-131-beta-30
	#314250
	314250.1-60
	314250.61-121
	#314255
	314255.1-131
	314255.132-262

	# xangle-130-beta-30
	#314269
	314269.1-86
	314269.87-172
	#314272
	314272.1-18
	314272.19-37

	# xangle-130-beta-25
	#314274
	314274.1-25
	314274.26-55
	314274.56-80
	#314276
	314276.1-80
	314276.81-160
	314276.161-230
)

SubmitTrackBasedAlignment
