#!/bin/bash

# what to optimise
sector="45"
z0="-210000"
rps="3,4,5,23,24,25"

# planes 4.4, 5.0, 5.1, 5.2, 5.3
excludePlanes="1981939712,1982332928,1982365696,1982398464,1982431232"

# event selection
minimumHitsPerProjectionPerRP=3
requireNumberOfUnits="2"
requireOverlap="False"
requireAtLeast3PotsInOverlap="True"

additionalAcceptedRPSets=""

# even number limit
#maxEvents="-1" # process all events
maxEvents="100000" # TODO

# iteration settings
iterations=4
#optimize=("s" "s" "sr")
optimize=("s")
maxResidualToSigma=(10 3)
chiSqPerNdfCut=(100 5)
maxTrackAx=("0.5E-3")
maxTrackAy=("0.5E-3")

# constraint settings
constraintsType="standard" # nothing else enabled
constraintsLabel="std"
final_constraints_units="1,21"

# diagonistics
iterationsWithDiagnostics="0"

# input settings
reco_dir="/eos/totem/data/ctpps/reconstruction/2018/alignment_run_April/version4"

# geometry settings
geometry="data/geometry/2018_April/2018_04_13_fill6554"

initial_alignment=("data/alignment/2018_April/s+el/version1/45.xml")

# output settings
subdir="tb,round2"
label=""  # for non-standard settings, e.g. ",test"

NewDataSet
tasks=(
	# xangle-160-beta-30
	#314247
	314247.1-20
	314247.21-40
	314247.41-61

	# xangle-131-beta-30
	#314250
	314250.1-60
	314250.61-121
	#314255
	314255.1-131
	314255.132-262

	# xangle-130-beta-30
	#314269
	314269.1-86
	314269.87-172
	#314272
	314272.1-18
	314272.19-37

	# xangle-130-beta-25
	#314274
	314274.1-25
	314274.26-55
	314274.56-80
	#314276
	314276.1-80
	314276.81-160
	314276.161-230
)

SubmitTrackBasedAlignment
