#!/bin/bash

# what to optimise
sector="45"
z0="-210000"
rps="3,4,5,23,24,25" # TODO
#rps="3,23"

# planes 4.4, 5.0, 5.1, 5.2, 5.3
excludePlanes="1981939712,1982332928,1982365696,1982398464,1982431232"

# event selection
minimumHitsPerProjectionPerRP=3
requireNumberOfUnits="2"
requireOverlap="False"
requireAtLeast3PotsInOverlap="True"

additionalAcceptedRPSets=""

# even number limit
#maxEvents="-1" # process all events
maxEvents="1000000" # TODO

# iteration settings
iterations=4
#optimize=("s" "s" "sr")
optimize=("s")
maxResidualToSigma=(260 20 10 3)
chiSqPerNdfCut=(10000 400 50 5)
maxTrackAx=("1" "10E-3")
maxTrackAy=("1" "10E-3")

# constraint settings
constraintsType="standard" # nothing else enabled
constraintsLabel="std"
final_constraints_units="1,21"

# diagonistics
iterationsWithDiagnostics="0"

# input settings
reco_dir="/eos/totem/data/ctpps/reconstruction/2017/alignment_run_July/version3"

# geometry settings
geometry="2017_07_08_fill5912"

#initial_alignment=(
#	"/afs/cern.ch/work/j/jkaspar/software/offline/704/src/TotemAlignment/RPData/LHC/2016_04_20_fill4828/version1/sr+el/45.xml"
#	"/afs/cern.ch/work/j/jkaspar/software/offline/704/src/TotemAlignment/RPData/LHC/2016_04_20_fill4828/version1/sr+el/56.xml"
#)

# output settings
subdir="tb,round1"
label=""  # for non-standard settings, e.g. ",test"

NewDataSet
tasks=(
	298593
	298594
	298596
	298597
)

SubmitTrackBasedAlignment
