#!/bin/bash

source das_block_submitter

runs=(
	323893
	323899
	323907
	323919
	323932
	323933
	323934
)

datasets=(
	#"/ZeroBias1/Run2018D-PromptReco-v2/AOD"	tape
	#"/ZeroBias2/Run2018D-PromptReco-v2/AOD"	tape
	#"/ZeroBias3/Run2018D-PromptReco-v2/AOD"	partly tape
	"/ZeroBias4/Run2018D-PromptReco-v2/AOD"
	#"/ZeroBias5/Run2018D-PromptReco-v2/AOD"	partly tape
	#"/ZeroBias6/Run2018D-PromptReco-v2/AOD"	tape
	"/ZeroBias7/Run2018D-PromptReco-v2/AOD"
	#"/ZeroBias8/Run2018D-PromptReco-v2/AOD"	tape
	#"/ZeroBias9/Run2018D-PromptReco-v2/AOD"	partly tape
	"/ZeroBias10/Run2018D-PromptReco-v2/AOD"
)

files_per_block="1"

output_dir="/eos/totem/data/offline/2018/450GeV/tests/ZeroBias/version1"

geometry="geometry/2018_900GeV_beta100/RP_Dist_Beam_Cent.xml"

alignment_dir=""
alignment_files=""

task_prefix="reco"
task_suffix="_reco"

queue="8nh"

template_file="config/450GeV/tests/reco_aod_template.py"

SubmitBlocks
